// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUFDdWb1f3B3oTiOz2s5pucJl8SFffvz0',
    appId: '1:659402577431:web:234b58b00093207ae2ee52',
    messagingSenderId: '659402577431',
    projectId: 'flutter-firebase-p-7fa1d',
    authDomain: 'flutter-firebase-p-7fa1d.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-p-7fa1d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-p-7fa1d.firebasestorage.app',
    measurementId: 'G-CZKNB8L270',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFNxXwBExfcczZInZ9Tx2INGg4KMBtzrQ',
    appId: '1:659402577431:android:c1ef9a22762badd6e2ee52',
    messagingSenderId: '659402577431',
    projectId: 'flutter-firebase-p-7fa1d',
    databaseURL: 'https://flutter-firebase-p-7fa1d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-p-7fa1d.firebasestorage.app',
  );
}
